### ISSUE TITLE
How to set InitializeParams.initializationOptions?

### ISSUE THREAD

**Issue by htfy96** [autozimu/LanguageClient-neovim#178]
I am trying to get this client working with [CQuery](https://github.com/jacobdufault/cquery), a new C++ language server. However, it reported that `FATL| Initialization parameters (particularily cacheDirectory) are required` in its log because during `initialize`, `initializationOptions.cacheDirectory` must be set. 

It seems that currently there is no way to set these options in this plugin. This problem also affects `clangd`, which by default works only in C++98 mode and considers all syntax in C++11 as errors. Is it possible to set `initializationOptions` with default values/callback functions?

Thanks.

**Comment by autozimu** [comment]
Resolved in ef2b82c41a864e8b26e58897e4bb7f4dd5576cd2.

**Comment by DeltaEvo** [comment]
I added a little wiki page to help to settup cquery with LanguageClient-neovim https://github.com/autozimu/LanguageClient-neovim/wiki/cquery

**Comment by akinh** [comment]
Was trying to fix this issue, and updated my autozimu/LanguageClient-neovim repo. However, getting 

```
error caught in async handler '/home/username/.vim/bundle/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:CursorMoved:* [['', 56]]'
Traceback (most recent call last):
  File "/home/username/.vim/bundle/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 1171, in handle_CursorMoved
    buftype, line = gather_args(["buftype", "line"], args=args)
  File "/home/username/.vim/bundle/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 75, in gather_args
    if len(args) > 1 and len(args[1]) > 0:  # from vimscript side
TypeError: object of type 'int' has no len()
```
this error now. Any ideas how to fix ?

**Comment by akinh** [comment]
UpdateRemotePlugins fixed it. Sorry for the noise.

**Comment by akinh** [comment]
Still getting the same error after updating the plugin and setting the params in .vim/settings.json. When I run cquery from command line, it works fine though.

**Comment by MaskRay** [comment]
It's better to have some way to use different initializationOptions for different language servers

```
{
        "initializationOptions": {
                "cacheDirectory": "/tmp/cquery",
		"resourceDirectory": "yourCQueryDirectory/clang_resource_dir"
        }
}
```

**Comment by oblitum** [comment]
That's right, I just asked about this here: https://github.com/autozimu/LanguageClient-neovim/issues/633#issuecomment-437675277.

**Comment by oblitum** [comment]
"Method2" of the Yaml wiki entry shows one possible way to circumvent this limitation, but it's a bit ugly: https://github.com/autozimu/LanguageClient-neovim/wiki/yaml-language-server, it uses `call LanguageClient#Notify('workspace/didChangeConfiguration', { 'settings': config })` to set a different `config` settings path per language on an autoload script.
